apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  labels:
    app: portfolio-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: 046432083464.dkr.ecr.eu-west-2.amazonaws.com/portfolio:2
          ports:
            - containerPort: 8080
          imagePullPolicy: Always