apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
#       - image: gcr.io/google-samples/node-hello:1.0
      - image: 046432083464.dkr.ecr.eu-west-2.amazonaws.com/portfolio:92
        name: test-app
        ports:
        - containerPort: 8080
