apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: 046432083464.dkr.ecr.eu-west-2.amazonaws.com/portfolio:2
        name: test-app
        ports:
        - containerPort: 8080
